name: "GoodKey Windows Code Signing"
description: "Automated code signing for Windows using the GoodKey service."
branding:
  icon: "lock"
  color: "green"
inputs:
  organization:
    description: "The organization identifier."
    required: true
  token:
    description: "The GoodKey API token."
    required: true

runs:
  using: "node20"
  main: "dist/index.js"
