on: push

name: Testing action
jobs:
  run_action:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Create test file
        run: echo "Hello, world!" > test.txt
      - name: Run the action
        uses: ./
        with:
          organization: ${{ secrets.ORGANIZATION }}
          token: ${{ secrets.TOKEN }}
          file: "test.txt"
      - name: Check the output
        run: cat test.txt
          
