on: push

name: Testing action
jobs:
  run_action:
    runs-on: windows-latest
    env:
      GOODKEY_ENV: "canary"
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Create test file
        run: |
          copy C:\Windows\System32\wmi.dll .
      - name: Run the action
        uses: ./
        with:
          organization: ${{ secrets.ORGANIZATION }}
          token: ${{ secrets.TOKEN }}
          certificate: "84f06ea86c3ebb39f72911cd167769711a57ad87"
          file: "*.dll"
          timestamp_rfc3161_url: "http://timestamp.digicert.com"
          timestamp_digest_algorithm: "sha256"
          description: "This is a test file"
          description_url: "https://example.com"
          file_digest_algorithm: "sha256"
          additional_certificates: |
            -----BEGIN CERTIFICATE-----
            MIIDUjCCAjqgAwIBAgIQIVfZvie6U4+z2YBWyNv+wDANBgkqhkiG9w0BAQsFADAx
            MRAwDgYDVQQDEwdEZW1vIENBMRAwDgYDVQQKEwdHb29kS2V5MQswCQYDVQQGEwJV
            UzAeFw0yNDA1MzAxMTAyNTlaFw0yNzA1MzAxMTAyNTlaMDExEDAOBgNVBAMTB0Rl
            bW8gQ0ExEDAOBgNVBAoTB0dvb2RLZXkxCzAJBgNVBAYTAlVTMIIBIjANBgkqhkiG
            9w0BAQEFAAOCAQ8AMIIBCgKCAQEA0gXd0YiJxCghZ0h1o37Gd6EOkFUGzmKhdDv8
            XJuk6ahtheRxmdw0tfB3jpIrK/a4ENKQGFIzsOYPH8xV/axB/mOcEN9bvOhWarPr
            LzGFjO0NeNxVBbYNO34avrAiMJX69CsGdSleyp0mL90TPu/vAjq8T7zwVXwLs0nI
            /Lr6QqA0xEdX5m7dsAajKBPzvrUb4GqGfbpf1/K1Ui0TuEp+wgz2/gXNDcdt5qvG
            yNlqX2xwO1B/xNI7ltew8ljpFEndNxsp4y0vfZ/W3KTxa2NTL5DXioCZO2lZC4sY
            Mem3IfSX6VFk/V9MHRZnyA4L/Yc+r6oSnLsWcLvCEYZfiEqVXwIDAQABo2YwZDAS
            BgNVHRMBAf8ECDAGAQH/AgEAMA4GA1UdDwEB/wQEAwIBBjAfBgNVHSMEGDAWgBQu
            79XB+iPTrXue7iUT0BtunX0D9jAdBgNVHQ4EFgQULu/Vwfoj0617nu4lE9Abbp19
            A/YwDQYJKoZIhvcNAQELBQADggEBAFXppZnHAtgwUc8VDHYloO5D/WR7O+ND7esX
            yjnBmKjJpIpYsZk7awNkkE9n6nXihenit1JbzQT0ERb6KJsVDYBPB9QF6bxbmh1W
            p62OmPxhO/XsbX2PjZ122wDOnGvqx3n65290fyCEp6EeBATV6l7qL4yHax2hb0Dz
            nKMK9gTqgtQxwQpwAyjjOEjb/WPETxrUbVlIrEKITaEMnsQ7EzQnkz6z9Xql/9AR
            5rHpuq01v0BhRfFyIBguKwn3QvVtDKbwTtPBKiMiVaXSdoMUq2/mzZgw0CnwzwKg
            5Rmczjr7XcD+0tIi+iQjzTrmOsf8b+teXSgwSgzKvn7ECwF5glE=
            -----END CERTIFICATE-----
            -----BEGIN CERTIFICATE-----
            MIIDbzCCAlegAwIBAgIQSP834NFgwzyiGQwy7YLFODANBgkqhkiG9w0BAQsFADAx
            MRAwDgYDVQQDEwdEZW1vIENBMRAwDgYDVQQKEwdHb29kS2V5MQswCQYDVQQGEwJV
            UzAeFw0yNTAyMTAxNzM0MDJaFw0yNjAyMTAxNzM0MDJaMD8xHjAcBgNVBAMTFUNv
            ZGVTaWduaW5nIEdpdEh1YiBDSTEQMA4GA1UEChMHR29vZEtleTELMAkGA1UEBhMC
            VVMwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQC4Yv28/UJk2Jz3y3FF
            QHjHYFeicFh7JKe3KJa0o01qRbHTUpjEvyiH/9cwW56PIBeoe1Urj7t+czakXwgc
            7PQChEnIPp2XWNMQtsCt9BV5a78DY+Ry2eRLm4/zcCdVV7G2bwU/SIqzFFcrg7hZ
            ngnRRlCMFF7cj8EuO/3zDDfl7rfB43PgfOKQyCYBu2JMWxJJxMKX0qT2G97pmxB6
            EqLHDDWSplRtUXU4l6km65HhCEDbPqB7b7q3t0SwN0/0udcJCMx+7LUFmRIGpuPS
            fZBw5AxvxeT3t1vUGtepDtPRnZTeLv4f+fCZAPBZ3yqeoWQpytCkRUZsOZbPXKje
            AbfdAgMBAAGjdTBzMAwGA1UdEwEB/wQCMAAwHwYDVR0jBBgwFoAULu/Vwfoj0617
            nu4lE9Abbp19A/YwHQYDVR0OBBYEFGFdm0diyjI8WJWvx/CIiTvD/nUTMA4GA1Ud
            DwEB/wQEAwIHgDATBgNVHSUEDDAKBggrBgEFBQcDAzANBgkqhkiG9w0BAQsFAAOC
            AQEAHykvKP8pmNmmkWp7yPceNtWvfw4BhFSsxZw0n+H0GA+OaC4/ymF4DYH+6R7j
            1Ty6aeAl6BuwUR1ATtcVuQjQklJUDsfWa/Fe3SHiDIHrcorKK+Ti5ZWt3iFnxrdp
            Wp5dFXrPaEyHlvggjPtme4K6mgzLdD5mw8ydVfTq2BOKbf2FsgTgmdXY1lYYSch4
            68X76GkjkWnbb5nlmYFqOc68PkC8akTHaEYDh9/DJRA2YweJcZO8bN6f1azmSdP2
            xpAWGFPYRqv0qO7hoKThLThiwF8IOvyqR4p+h9z5jSzHa46BaYy9xCsFkvsp0SO1
            ChV9NhhlNQYeQrBf0mVUjdebHw==
            -----END CERTIFICATE-----
      - name: Upload signed
        uses: actions/upload-artifact@v4
        with:
          name: signed
          path: wmi.dll
