on: push

name: Testing action
jobs:
  run_action:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Create test file
        run: |
          copy C:\Windows\System32\wmi.dll . 
      - name: Run the action
        uses: ./
        with:
          organization: ${{ secrets.ORGANIZATION }}
          token: ${{ secrets.TOKEN }}
          file: "wmi.dll"
          
